### ISSUE TITLE
Note for kinase genes

### ISSUE THREAD

**Issue by brannonar** [andurill/sv_annotator#1]
Please automate the following note for any kinase gene that could be targeted (NTRK1, NTRK2, NTRK3, FGFR1, FGFR2, FGFR3, BRAF, ALK, EGFR, RET, ROS1,...) when there is any SV that does not form a predicted fusion event involving the kinase domain.  

“The [specific kinase gene] rearrangement detected results in [what did this do on impact]. Further testing to determine the presence or absence of a targetable oncogenic fusion involving [specific gene] is needed, and this sample has been nominated for further analysis using the Archer targeted RNAseq assay. Archer will be performed and reported under a separate accession number if additional material is available.”

**Comment by andurill** [comment]
Fixed. Refer to commit 1a443d9
